[variables]
PYTHON_VERSION = "3.11"

[phases.build]
cmds = [
    "pip install -r railway-requirements.txt",
    "mkdir -p /app/data/transcriptions /app/data/uploads /app/logs"
]

[phases.start]
cmd = "cd api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
